# Site settings
title: Demon of the Second Kind
email: kimhyunkang@gmail.com
description: "A microblog about Rust and other stuff"
baseurl: "/blog"
url: "http://kimhyunkang.github.io"

# Build settings
markdown: kramdown
permalink: pretty
