# Site settings
title: English Patient
email: kimhyunkang@gmail.com
description: "A microblog about Rust and other stuff"
baseurl: ""
url: "http://kimhyunkang.github.io"

# Build settings
markdown: kramdown
permalink: pretty
